// // import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({ children }) {
// //   return (
// //     <html lang="en">
// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// //       >
// //         {children}
// //       </body>
// //     </html>
// //   );
// // }













// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { SocketProvider } from "./socketconetxprovider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {/* ✅ Wrap with SocketProvider */}
//         <SocketProvider>
//           {children}
//         </SocketProvider>
//       </body>
//     </html>
//   );
// }













import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ChatProvider } from "./context/chatcontext";
import ReduxProvider from "./rtk/reduxprovider";
import IncomingCall from "./calling/page";
import Layoutbar from "./component/layoutbar";
import ChatVerticalLayout from "./component/layoutbar";
import ChatSidebarLayout from "./component/layoutbar";
import WhatsApplayout from "./dummy/layoutt";









// ✅ aapka context import

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Chat App",
  description: "Realtime chat using Next.js + Socket.io",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* ✅ Yaha wrap karna hota hai */}
        <WhatsApplayout />
        <ChatProvider>

          {children}
          <IncomingCall />
        </ChatProvider>


      </body>
    </html>
  );
}
